# Generated by Django 3.1.4 on 2020-12-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorFullName', models.CharField(max_length=256, verbose_name='Полная имя доктора')),
                ('firstName', models.CharField(max_length=128, verbose_name='Имя доктора')),
                ('secondName', models.CharField(max_length=128, verbose_name='Фамилия доктора')),
                ('lastName', models.CharField(max_length=128, verbose_name='Отчество доктора')),
                ('doctorPhoneNumber', models.PositiveIntegerField(verbose_name='Номер телефона доктора')),
                ('doctorEducation', models.TextField(verbose_name='Образование доктора')),
                ('doctorImage', models.ImageField(null=True, upload_to='doctorsImage/')),
                ('doctorInfo', models.TextField(verbose_name='Информация о доктора')),
                ('doctorStatus', models.CharField(max_length=128, verbose_name='Статус доктора')),
                ('doctorWorkLocation', models.CharField(max_length=512, verbose_name='Адресс работы доктора')),
                ('doctorType', models.CharField(max_length=256, verbose_name='Профессия доктора')),
            ],
        ),
    ]
