# Generated by Django 3.1.4 on 2021-02-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortype',
            name='image',
            field=models.ImageField(null=True, upload_to='doctor_type/'),
        ),
        migrations.AddField(
            model_name='medicalstaffpositions',
            name='image',
            field=models.ImageField(null=True, upload_to='medical_staff/'),
        ),
    ]
