# Generated by Django 3.1.4 on 2020-12-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название специалиста')),
            ],
            options={
                'verbose_name': 'Профессия специалиста',
                'verbose_name_plural': 'Профессии специалистов',
            },
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Специалиста', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='doctorType',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doctorEducation',
            field=models.TextField(verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doctorFullName',
            field=models.CharField(max_length=256, verbose_name='Фамилия Имя Отчество'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doctorInfo',
            field=models.TextField(verbose_name='Информация о специалиста'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doctorPhoneNumber',
            field=models.PositiveIntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doctorStatus',
            field=models.CharField(max_length=128, verbose_name='Статус специалиста'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doctorWorkLocation',
            field=models.CharField(max_length=512, verbose_name='Адресс работы специалиста'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='firstName',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='lastName',
            field=models.CharField(max_length=128, verbose_name='Отчество '),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='secondName',
            field=models.CharField(max_length=128, verbose_name='Фамилия'),
        ),
    ]
