# Generated by Django 3.1.4 on 2020-12-20 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20201220_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doctorType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctortype'),
        ),
    ]
