# Generated by Django 3.1.4 on 2020-12-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctors_doctortype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStaffPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Должность специалиста')),
            ],
            options={
                'verbose_name': 'Должность специалиста',
                'verbose_name_plural': 'Должности специалистов',
            },
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doctorType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctortype', verbose_name='Профессия специалиста'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='medical_staff_positions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.medicalstaffpositions', verbose_name='Должность'),
        ),
    ]
