# Generated by Django 3.1.4 on 2020-12-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20201221_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstaffpositions',
            name='medical_staff_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество объявлений'),
        ),
    ]
