# Generated by Django 3.1.4 on 2020-12-25 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0005_medicalstaffpositions_medical_staff_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='user_ownre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
