# Generated by Django 3.1.4 on 2020-12-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctors_user_ownre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='user_ownre',
            new_name='user_owner',
        ),
    ]
